function gitStashAndClear(){
  git stash
  git stash clear
}


alias gitClean=gitStashAndClear
alias gitUpdate='git checkout master && git pull && git checkout - && git merge master'
alias ls='ls -la'
alias mkdir='mkdir -p'
alias kube='kubectl'
alias reloadBash='. ~/.bash_profile'

alias got='git'
alias emasc='emacs'
alias bake='make'
